var GAME_LEVELS = [
["                                                                                                                    ",
 "                                                                                                                    ",
 "                                                                                                                    ",
 "                                                                                                                    ",
 "                                        ttttttttttttt                                                               ",
 "                                         c    t                                                                     ",
 "                                              t                                                                     ",
 "                                              tttt                                              ttttttttttttttt     ",
 "                                              t c                                                 c        t        ",
 "  x                                           t                                                           t         ",
 "  x                                        o  t                                                           t         ",
 "  x@                                  xxxxxxxxx                                                           tttttt    ",
 "  xxxx                              o x                                                                   t    c    ",
 "  xxxx                            xxxxx                                                         o         t         ",
 "  xxxx                                                                  o                     xxxxxx      t         ",
 "  xxxx          xxxx                       xxxxxx                    xxxx                                 t         ",
 "  xxxx          xxxx     o    o    o                                 xxxx             o    o    o       oot         ",
 " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!xxxxxxxxxxxxxxxx!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   ",
 "                                                      x!!!!x              x!!!!x                                    ",
 "                                                      xxxxxx              xxxxxx                                    ",
 "                                                                                                                    ",
 "                                                                                                                    ",
 "                                                                                                                    "],
["                                                                                                                                            ",
 "  x                                                                                                                                         ",
 "  x                                                                                                                                         ",
 "  x  @                                                                  ttttttttttttttt                                                     ",
 "  xxxxxxxxxx                                 d                           c       t    c                                                     ",
 "                    o                      xxxxxx                                t                               tttttttttttttt             ",
 "                 xxxxxxxx                                                        t                                c   xxxxx  c              ",
 "                                                                                 t                                                          ",
 "             o                    o                     o                        t                                                          ",
 "         xxxxxxxxxx           xxxxxxxxxxx            xxxxxxxx      xxxx      xxxxxxxx                                                       ",
 "                                                                                                                                            ",
 "                                                                                                                                            ",
 "                                        o                             o                                o                                    ",
 "   xxxxx            xxxxxx    xx      xxxxxxx              xxxx     xxxxxx                           xxxxxxx                      o         ",
 "                                                   o                                        o                         o       xxxxxxxx      ",
 "            o                                  xxxxxxxx                         o        xxxxxx        o   xxxx     xxxxxx           x      ",
 "        xxxxx                           o                                     xxxxx                 xxxxxxx                          x      ",
 "                      o                 xxx                                                                                          x      ",
 "    x!!!!!!!!!!!xxxxxxxxxxxxx!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x      ",
 "    xxxxxxxxxxxxx           x!!!!x                         x!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x      ",
 "                            xxxxxx                         x!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x      ",
 "                                                           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx      ",
 "                                                                                                                                            ",
 "                                                                                                                                            ",
 "                                                                                                                                            "],
["                                                                                                                                               ",
 "                                                                                                                                               ",
 "                                                                                                                                               ",
 "                                                                                                                                               ",
 "                                                                                                                                               ",
 "                                                                                                                                               ",
 "                                                                                                                                               ",
 "                                       o            @     o                                                                                    ",
 "                                     xxxxx       xxxxx   xxxxx                                                                                 ",
 "           o              o                                                                                                 xxx                ",
 "        xxxxxxxxxxxx!!xxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxx                         o                                          ",
 "                   x!!x          x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x         x                    xxxxxxxxxxx                                     ",
 "                   xxxx          x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x         x         o                               o       o                  ",
 "                                 x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x         xxxxxxxxxxxxxxxxxxxx!!!!!!!!xxxxx!!!!!!!xxxxxxxxxxxxxxxxxx       xx  ",
 "                                 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                            x!!!!!!!!xxxxx!!!!!!!x                xx      xx  ",
 "                                                                                             xxxxxxxxxxxxxxxxxxxxxx                x       xx  ",
 "                                                                                                                                   x       xx  ",
 "                                                                                                                                   x       xx  ",
 "    tttttt                                                                                                                         x      xxx  ",
 "    t   c                                          o                                                                                       xx  ",
 "    t                                           xxxxxxx                                                                                    xx  ",
 "    t                                                 x                o                                o                                 xxx  ",
 "    t                          xxxxx                  xxxxx          xxxxxxx                          xxxxxxx       xxxx        o      o   xx  ",
 "    t      o       o                          o                                    xxxxx                                    xxxxxxxxxxxxxxxxx  ",
 " xxxxxxxxxx       xxxx                     xxxxxx                         xxxxx               xxxxxx                                           ",
 " x                                                                                                                                             ",
 " x                                                                                                                                             ",
 " x            xxxxxxx                                 xxxx                                                                                     ",
 " x                                                                                                                                             ",
 " x                                        xxxx                                                                                                 ",
 " x    o                                                       o                                      o              o                   o      ",
 " xxxxxxxxxxxxx!!!!!!!!!xxxxx!!!!!!xxxx!!!!!!!!!!!xxx!!!!!!!!xxxxxx!!!!!!!!!!!xxxxxx!!!!!xxxx!!!!!!!xxxxxx!!!!!!!xxxxxxxxxx!!!!!!!!!xxxxxxxxxx  ",
 "             x!!!!!!!!!xxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx  ",
 "             x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx  ",
 "             x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx  ",
 "             xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
 "                                                                                                                                               ",
 "                                                                                                                                               "],
["                                                                                                                    ",
 "                                                                                                                    ",
 "                                                                                                                    ",
 "                                                                                                                    ",
 "                                                                                                                    ",
 "                                                                                                                    ",
 "                                                                                                                    ",
 "                                                                                                                    ",
 "                                                                                                                    ",
 "  x                                                                            d                                    ",
 "  x                                        x    x                                                                   ",
 "  x@                                        x x   xxxx   x  x     x        x   x    xxxxx                           ",
 "  xxxx                                       x    x  x   x  x     x   x    x   x    x   x                           ",
 "  xxxx                                       x    x  x   x  x      x x  x x    x    x   x                           ",
 "  xxxx                                       x    xxxx   xxxx       x    x     x    x   x                           ",
 "  xxxx                                                                                                              ",
 "  xxxx                    o                 o                     o                 o          o          o         ",
 " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
 "                                                                                                                    ",
 "                                                                                                                    ",
 "                                                                                                                    ",
 "                                                                                                                    ",
 "                                                                                                                    "],
];
   if (typeof module != "undefined" && module.exports)
   module.exports = GAME_LEVELS;
